#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/opt/gwt-mac-1.5.0/gwt-user.jar:/opt/gwt-mac-1.5.0/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/WebContent" "$@" eu.stupidsoup.backpack.BackpackView;
